<?php
namespace CTLib\Tests\Util;

use CTLib\Util\Arr;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-02-11 at 14:27:27.
 */
class ArrTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Arr
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Arr;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }


    /**
     * @group unit
     * @group DoNotTest
     * @covers CTLib\Util\Arr::get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @group unit
     * @group DoNotTest
     * @covers CTLib\Util\Arr::mustGet
     * @todo   Implement testMustGet().
     */
    public function testMustGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @group unit
     * @group DoNotTest
     * @covers CTLib\Util\Arr::extract
     * @todo   Implement testExtract().
     */
    public function testExtract()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @group unit
     * @group DoNotTest
     * @covers CTLib\Util\Arr::mustExtract
     * @todo   Implement testMustExtract().
     */
    public function testMustExtract()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @group unit
     * @group DoNotTest
     * @covers CTLib\Util\Arr::find
     * @todo   Implement testFind().
     */
    public function testFind()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @group unit
     * @group DoNotTest
     * @covers CTLib\Util\Arr::mustFind
     * @todo   Implement testMustFind().
     */
    public function testMustFind()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @group unit
     * @group DoNotTest
     * @covers CTLib\Util\Arr::findAll
     * @todo   Implement testFindAll().
     */
    public function testFindAll()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @group unit
     * @group DoNotTest
     * @covers CTLib\Util\Arr::exists
     * @todo   Implement testExists().
     */
    public function testExists()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @group unit
     * @group DoNotTest
     * @covers CTLib\Util\Arr::findByKeyChain
     * @todo   Implement testFindByKeyChain().
     */
    public function testFindByKeyChain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @group unit
     * @group DoNotTest
     * @covers CTLib\Util\Arr::isAssociative
     * @todo   Implement testIsAssociative().
     */
    public function testIsAssociative()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @group unit
     * @group DoNotTest
     * @covers CTLib\Util\Arr::concatValues
     * @todo   Implement testConcatValues().
     */
    public function testConcatValues()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @group unit
     * @group DoNotTest
     * @covers CTLib\Util\Arr::match
     * @todo   Implement testMatch().
     */
    public function testMatch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
